apiVersion: apps/v1
kind: Deployment
metadata:
  name: readit-cart
spec:
  selector:
    matchLabels:
      app: readit-cart
  template:
    metadata:
      labels:
        app: readit-cart
    spec:
      containers:
      - name: readit-cart
        image: bookshopacrapp101.azurecr.io/cart:latest

        ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: readit-cart
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5004
  selector:
    app: readit-cart      
